---
abstract: 'Finance::SEC::Edgar provides downloads of SEC EDGAR filings'
author:
  - 'Vikas N. Kumar <vikas@cpan.org>'
build_requires:
  File::Spec: 0
  Module::Build: 0
  Test::More: 0
configure_requires:
  Module::Build: 0
  Software::License: 0
dynamic_config: 1
generated_by: 'Module::Build version 0.4203, CPAN::Meta::Converter version 2.132830'
keywords:
  - finance
  - SEC
  - Edgar
  - filings
  - securities
  - companies
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Finance-SEC-Edgar
no_index:
  directory:
    - t
provides:
  Finance::SEC::Edgar:
    file: lib/Edgar.pm
    version: 0.01
  Finance::SEC::Edgar::Downloader:
    file: lib/Edgar/Downloader.pm
    version: 0.01
  Finance::SEC::Edgar::Parser:
    file: lib/Edgar/Parser.pm
    version: 0.01
recommends:
  Finance::QuoteHist: 0
  PGPLOT: 0
requires:
  DateTime: 0
  LWP: 0
  LWP::UserAgent: 0
  Regexp::Common: 0
  perl: v5.10.0
resources:
  bugtracker: https://github.com/vikasnkumar/finance-sec-edgar/issues
  license: http://dev.perl.org/licenses/
  repository: https://github.com/vikasnkumar/finance-sec-edgar
version: 0.01
